### ISSUE TITLE
Route [admin.servergateway.index] is not defined` error by creating CRUD with Tomato/PHP

### ISSUE THREAD

**Issue by chegmarco1989** [tomatophp/tomato-php#11]
Hello.

Unable to generate CRUD. When I try to generate my first CRUD by following this link: https://docs.tomatophp.com/get-started/start-your-first-crud. 
But After create and make `servergateway` migration, I add in `app\Providers\AppServiceProvier`, this following in its `boot` method:

```
use TomatoPHP\TomatoAdmin\Facade\TomatoMenu;
use TomatoPHP\TomatoAdmin\Services\Contracts\Menu;

... 

public function boot()
{
    TomatoMenu::register(
        Menu::make()
            ->group('Resources')
            ->label('Users')
            ->route('admin.servergateway.index')
            ->icon('bx bx-user')
    );
}
```

I get `Route [admin.servergateway.index] is not defined` error.

**Does Documentation about How to create a first CRUD is really complete ???** 

Otherwise, please help me to fix that error and succeed my CRUD's creation.

Awaiting your reply.
Thanks.

**Comment by fadymondy** [comment]
TomatoMenu add a menu to side menu with the route name and before generate this route not exists and it's a laravel route error not Tomato, so please make a generate first and then add your menu to the provider

**Comment by chegmarco1989** [comment]
I don't understand clearly. So, what is your advise to fix that `Route Not found` error ???

Also, is there any way to custom new generated Controller and View. If so, where to found them because, I don't see them in `App\Http\Controllers` and `Resources\views` folders.

**Comment by chegmarco1989** [comment]
Or do I just need to follow this link: https://docs.tomatophp.com/tomato-admin/generate-crud and forget adding to provider ???

**Comment by fadymondy** [comment]
you need to generate the CRUD first than add to the provider.
