### ISSUE TITLE
Method Illuminate\Database\PostgresConnection::getDoctrineSchemaManager does not exist.

### ISSUE THREAD

**Issue by oggiesutrisna** [tomatophp/tomato-php#12]
Trying to install TomatoPHP, im trying to do this commands `composer require tomatophp/tomato-php` it shows issues above. Is it me or maybe your packages just got a issue. Im trying to fix this using postgres and sqlite it same. 
![image](https://github.com/tomatophp/tomato-php/assets/40566790/b2bdbcb2-0ab1-443a-98cb-81cb09914ad2)

**Comment by Smdev4u** [comment]
Hi, I think you need to enable the extension in your php.ini file.

**Comment by fadymondy** [comment]
fixed on last release
