### ISSUE TITLE
mkdir(): Not a directory

### ISSUE THREAD

**Issue by dhsont** [tomatophp/tomato-php#7]
I installed tomato and trying customer example crud

got error after do you want to use form builder ? "mkdir(): Not a directory"

`
 🍅 Please input your module name? (ex: Translations):
 > Customer  

🍅 Module not found but we will create it for you

 🍅 Do you went to use Form Builder? (form/file) [form]:
 > form

mkdir(): Not a directory`

**Comment by fadymondy** [comment]
done on the new release v1.1.0
